import { Injectable } from '@angular/core';

export interface UrbanoInterface {
    urbano: string,
    analistadeiu: string,
    folio_ingreso          : string,
    fecha_ingreso          : string,
    consecutivo_dgu        : string,
    cuenta_catastral       : string,
    modalidad_tramite      : string,
    tipo_obra              : string,
    calle                  : string,
    numero_oficial         : string,
    colonia                : string,
    alcaldia               : string,
    denominacion_proyecto  : string,
    razon_social           : string,
    representante_legal    : string,
    pdu                    : string,
    registro_pdu           : string,
    dro                    : string,
    registro_dro           : string,
    uso_proyecto           : string,
    zonificacion           : string,
    instrumento_normativo  : string,
    m2_predio              : string,
    superficie_construccion: string,
    niveles_permitido      : string,
    niveles_snb            : string,
    niveles_bnb            : string,
    construccion_snb       : string,
    construccion_bnb       : string,
    construccion_total     : string,
    no_viviendas           : string,
    cajones_estacionamiento: string,
    biciestacionamiento    : string,
    prevencion             : string,
    asociacion             : string,
    poligono_actuacion     : string,
    proyectos              : string,
    donacion               : string,
    estatus                : string
};


@Injectable({
    providedIn: 'root'
})
export class impactourbanoservice {

    public data:<UrbanoInterface>[] = [
        {
            urbano:"1",
            analista_deiu:'Cecilia',
            folio_ingreso:' 29201-121DIED16 ',
            fecha_ingreso:'42496',
            consecutivo_dgu:'022/16',
            cuenta_catastral:'756-014-02',
            modalidad_tramite:'EIU',
            tipo_obra:'Obra Nueva ',
            calle:'Carretera México Toluca  ',
            numero_oficial:'5214',
            colonia:'Col. El Yaqui.',
            alcaldia:'Cuajimalpa',
            denominacion_proyecto:'U-Storage',
            razon_social:'Servicio Funerarios Lomas, S.A. de C.V.',
            representante_legal:'C. Eduardo Diez Barroso Salido',
            pdu:'Arq. Jaime Bolaños Rojas',
            registro_pdu:'0075',
            dro:'Arq. Sergio Federico García Hernandez',
            registro_dro:'0531',
            uso_proyecto:'Bodega y oficinas ',
            zonificacion:'HM/15/30   ',
            instrumento_normativo:'Norma 10',
            m2_predio:'2400',
            superficie_construccion:'25200',
            niveles_permitido:'15',
            niveles_snb:'10',
            niveles_bnb:'3',
            construccion_snb:'10649.6',
            construccion_bnb:'3237.19',
            construccion_total:'13886.79',
            no_viviendas:'NA',
            cajones_estacionamiento:'65',
            biciestacionamiento:'NA',
            prevencion:'No requirio ',
            asociacion:'_',
            poligono_actuacion:'-',
            proyectos:'Carretera Mex-Tol',
            donacion:'_',
            estatus:'En proceso ',
        },
        {
            urbano:'10',
            analista_deiu:'Ernesto',
            folio_ingreso:'25855-121FEHU17 ',
            fecha_ingreso:'12/04/17 ',
            consecutivo_dgu:'021/17 ',
            cuenta_catastral:'039-027-04',
            modalidad_tramite:'EIU',
            tipo_obra:'Ampl/Mod',
            calle:'Av. Revolución',
            numero_oficial:'725',
            colonia:'Col. Nonoalco.',
            alcaldia:'Benito Juárez',
            denominacion_proyecto:'Torre Revolución',
            razon_social:'Rouz Bienes Raíces, S.A. de C.V. ',
            representante_legal:'C. Hugo Enrique Fernández Cortés',
            pdu:'Arq. Beatríz Eugenia Bautista Santoyo',
            registro_pdu:'0414',
            dro:'Arq. Oscar Ramón Núñez Sánchez',
            registro_dro:'0479',
            uso_proyecto:'Oficinas y comercio ',
            zonificacion:'HM/15/34.51',
            instrumento_normativo:'Poligono de Actuación ',
            m2_predio:'3627.24',
            superficie_construccion:'23214.34',
            niveles_permitido:'15',
            niveles_snb:'15',
            niveles_bnb:'7',
            construccion_snb:'21425.12',
            construccion_bnb:'25039',
            construccion_total:' 46,464.12',
            no_viviendas:'NA',
            cajones_estacionamiento:'921',
            biciestacionamiento:'NA',
            prevencion:'No requirio ',
            asociacion:'_',
            poligono_actuacion:'Sí',
            proyectos:'',
            donacion:'No',
            estatus:'En proceso ',
        }
    ];

    public dataSelected:<UrbanoInterface> = {
        urbano: "",
        analistadeiu: "",
        folio_ingreso: "",
        fecha_ingreso: "",
        consecutivo_dgu: "",
        cuenta_catastral: "",
        modalidad_tramite: "",
        tipo_obra: "",
        calle: "",
        numero_oficial: "",
        colonia: "",
        alcaldia: "",
        denominacion_proyecto: "",
        razon_social: "",
        representante_legal: "",
        pdu: "",
        registro_pdu: "",
        dro: "",
        registro_dro: "",
        uso_proyecto: "",
        zonificacion: "",
        instrumento_normativo: "",
        m2_predio: "",
        superficie_construccion: "",
        niveles_permitido: "",
        niveles_snb: "",
        niveles_bnb: "",
        construccion_snb: "",
        construccion_bnb: "",
        construccion_total: "",
        no_viviendas: "",
        cajones_estacionamiento: "",
        biciestacionamiento: "",
        prevencion: "",
        asociacion: "",
        poligono_actuacion: "",
        proyectos: "",
        donacion: "",
        estatus: ""
    };

    constructor() {

    }


}
